// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float ph;
CloudTemperatureSensor temperatura;
CloudPercentage insolacao;
CloudPercentage umidade_solo;

void initProperties(){

  ArduinoCloud.addProperty(ph, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(insolacao, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(umidade_solo, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
